version: "3.8"
name: aims

services:
  grading-db:
    image: mongo:latest
    container_name: grading_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aims
      - MONGO_INITDB_ROOT_PASSWORD=aims
    ports:
      - "27018:27017"
    volumes:
      - grading_db_data:/data/db
      - grading_db_config:/data/configdb

  grading-ms:
    build: .
    image: aims_grading_ms
    container_name: grading_ms
    depends_on:
      - grading-db
    links:
      - grading-db
    environment:
      - MONGO_URI=mongodb://aims:aims@grading-db:27017
      - MONGO_DB=aims
    ports:
      - "8000:8000"

volumes:
  grading_db_data:
  grading_db_config:
