version: "3.8"
name: aims

services:
  grading_db:
    image: mongo:latest
    container_name: grading_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aims
      - MONGO_INITDB_ROOT_PASSWORD=aims
    ports:
      - "27018:27017"
    volumes:
      - grading:/data/db

  grading_ms:
    build: .
    image: aims_grading_ms
    container_name: grading_ms
    depends_on:
      - grading_db
    links:
      - grading_db
    environment:
      - MONGO_URI=mongodb://aims:aims@grading_db:27017
      - MONGO_DB=aims
    ports:
      - "8000:8000"

volumes:
  grading: